apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 20
  selector:
    app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nigelpoulton/pluralsight-docker-ci:latest
          ports:
            - containerPort: 8080
